require 'pathname'

ws_dir = Pathname.new(__dir__)
ws_dir = ws_dir.parent until
  File.exist?("#{ws_dir}/node_modules/react-native-macos/scripts/react_native_pods.rb") ||
  ws_dir.expand_path.to_s == '/'
require "#{ws_dir}/node_modules/react-native-macos/scripts/react_native_pods.rb"

prepare_react_native_project!

# Pod::Project#group_for_path_in_group calls base_path.realdirpath, which
# intermittently raises "pathname contains null byte" on CI when the local
# React pods resolve through pnpm's node_modules symlinks
# (https://github.com/CocoaPods/CocoaPods/issues/12798,
# https://github.com/CocoaPods/CocoaPods/issues/12866). Body copied from
# CocoaPods 1.16.2/1.17.0 (project.rb is identical in both) with realdirpath
# replaced by cleanpath, which never resolves the symlink. Drop this once
# upstream fixes the crash.
module PodsNullbyteWorkaround
  def group_for_path_in_group(absolute_pathname, group, reflect_file_system_structure, base_path = nil)
    unless absolute_pathname.absolute?
      raise ArgumentError, "Paths must be absolute #{absolute_pathname}"
    end
    unless base_path.nil? || base_path.absolute?
      raise ArgumentError, "Paths must be absolute #{base_path}"
    end

    relative_base = base_path.nil? ? group.real_path : base_path.cleanpath
    relative_pathname = absolute_pathname.relative_path_from(relative_base)
    relative_dir = relative_pathname.dirname

    if reflect_file_system_structure
      path = relative_base
      relative_dir.each_filename do |name|
        break if name.to_s.downcase.include? '.lproj'
        next if name == '.'
        path += name
        group = group.children.find { |c| c.display_name == name } || group.new_group(name, path)
      end
    end

    if relative_dir.basename.to_s.downcase.include? '.lproj'
      group_name = variant_group_name(absolute_pathname)
      lproj_parent_dir = absolute_pathname.dirname.dirname
      group = @variant_groups_by_path_and_name[[lproj_parent_dir, group_name]] ||=
                group.new_variant_group(group_name, lproj_parent_dir)
    end

    group
  end
end

Pod::Project.prepend(PodsNullbyteWorkaround)

target 'T3CodeRN-macOS' do
  platform :macos, '14.0'
  use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => '../node_modules/react-native-macos',
    :fabric_enabled => ENV['RCT_NEW_ARCH_ENABLED'] == '1',
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(installer)
  end
end
